steps:
  - command:
      - auto/build.sh
      - auto/deploy_dev.sh
    label: ":package: & :rocket: Build & Deploy Dev: VERSION -> ${BUILDKITE_BUILD_NUMBER}"
    branches: dev
    agents:
      queue: "wo:nonprod"
    retry:
      automatic:
        - exit_status: -1
          limit: 1
    env:
      BUILD_VERSION: "${BUILDKITE_BUILD_NUMBER}"
      ENV: "dev"
          
  - command:
      - auto/build.sh
      - auto/deploy_qa.sh
    label: ":package: & :rocket: Build & Deploy QA: VERSION -> ${BUILDKITE_BUILD_NUMBER}"
    branches: release/*
    agents:
      queue: "wo:qa"
    retry:
      automatic:
        - exit_status: -1
          limit: 1
    env:
      BUILD_VERSION: "${BUILDKITE_BUILD_NUMBER}"
      ENV: "qa"

  - wait

  - block: ":green_button: Deploy to PRE-PROD"
    prompt: "Deploy WO to PRE-PROD environment?"
    branches: "master"

  - command:
      - auto/build.sh
      - auto/deploy_preprod.sh
    label: ":package: & :rocket: Build & Deploy PRE-PROD: VERSION -> ${BUILDKITE_BUILD_NUMBER}"
    branches: master
    agents:
      queue: "wo:preprod"
    retry:
      automatic:
        - exit_status: -1
          limit: 1
    env:
      BUILD_VERSION: "${BUILDKITE_BUILD_NUMBER}"
      ENV: "preprod"

  - wait

  - block: ":green_button: Deploy to PROD"
    prompt: "Deploy WO to PROD environment?"
    branches: "master"

  - command:
      - auto/build.sh
      - auto/deploy_prod.sh
    label: ":package: & :rocket: Build & Deploy PROD: VERSION -> ${BUILDKITE_BUILD_NUMBER}"
    branches: master
    agents:
      queue: "wo:prod"
    retry:
      automatic:
        - exit_status: -1
          limit: 1
    env:
      BUILD_VERSION: "${BUILDKITE_BUILD_NUMBER}"
      ENV: "prod"    
