export const PAYMENT_MANAGEMENT = 'userPaymentManagement'

export const paymentManagementTranslation = {
  en: {
    translation: {
      [PAYMENT_MANAGEMENT]: {
        table: {
          email: 'Email',
          firstName: 'First Name',
          lastName: 'Last Name',
          type: 'Type',
          contact: 'Contact',
          state: 'State',
          bankName: 'Bank Name',
          cardBrand: 'Card Brand',
          bankNameOrCardBrand: 'Bank Name/Card Brand',
          last4Digits: 'Last 4 digits',
          expiration: 'Expiration'
        },
        modal: {
          new: 'New',
          cardNumber: 'Card Number',
          expirationDate: 'Expiration Date',
          cvc: 'CVC',
          creditCardInformation: 'Credit Card Information',
          cardHolderInformation: 'Card Holder Information',
          firstName: 'First Name',
          lastName: 'Last Name',
          contactNumber: 'Contact Number',
          email: 'Email',
          billingAddress: 'Billing Address',
          address: 'Address',
          city: 'City',
          state: 'State',
          zipCode: 'Zip Code',
          save: 'Save',
          update: 'Update',
          cancel: 'Cancel',
          selectAnOptionToContinue: 'Please Select An Option To Continue',
          accountType: 'Account Type',
          newCreditCard: 'New Credit Card',
          updateCreditCard: 'Update Credit Card',
          newAchForm: "New ACH Form",
          updateAchForm: "Update ACH Form",
        },
      },
    },
  },
  es: {
    translation: {
      [PAYMENT_MANAGEMENT]: {
        table: {
          email: 'Correo electrónico',
          firstName: 'Primer nombre',
          lastName: 'Apellido',
          type: 'Tipo',
          contact: 'Contacto',
          state: 'Estado',
          bankName: 'Nombre del Banco',
          cardBrand: 'Marca de la Tarjeta',
          bankNameOrCardBrand: 'Nombre del Banco/Marca de la Tarjeta',
          last4Digits: 'Últimos 4 dígitos',
          expiration: 'Expiración'
        },
        modal: {
          new: 'Nuevo',
          cardNumber: 'Número de Tarjeta',
          expirationDate: 'Fecha de Expiración',
          cvc: 'CVC',
          creditCardInformation: 'Información de la Tarjeta de Crédito',
          cardHolderInformation: 'Información del Titular de la Tarjeta',
          firstName: 'Nombre',
          lastName: 'Apellido',
          contactNumber: 'Número de Contacto',
          email: 'Correo electrónico',
          billingAddress: 'Dirección de Facturación',
          address: 'Dirección',
          city: 'Ciudad',
          state: 'Estado',
          zipCode: 'Código Postal',
          save: 'Guardar',
          update: 'Actualizar',
          cancel: 'Cancelar',
          selectAnOptionToContinue: 'Por favor seleccione una opción para continuar',
          accountType: 'Tipo de Cuenta',
          newCreditCard: 'Nueva Tarjeta de Crédito',
          updateCreditCard: 'Actualizar Tarjeta de Crédito',
          newAchForm: "Nuevo Formulario ACH",
          updateAchForm: "Actualizar Formulario ACH",
        },
      },
    },
  },
}
